### PR TITLE
Feature installer no tests

### PR DESCRIPTION
**Pull request by trein**
- Prevent test modules from being installed along with library modules.

### CODE REVIEW

**Comment by ankostis** [comment]
@trein Have you tried contacting @KurtSteinkraus about your PRs?

**Comment by trein** [comment]
@ankostis No, I haven't. At that time I assumed the project was active. Now I'm not sure anymore.

**Comment by ankostis** [comment]
I'm trying to contact him, and offering to maintain this project.
In any case, it would be good to have your PR merged and a new version uploaded into PyPi.

**Comment by AO-StreetArt** [comment]
@ankostis Were you ever able to get a hold of him?

Perhaps it's time someone just forks this repo and we go from there

**Comment by ankostis** [comment]
No :-(

**Comment by AO-StreetArt** [comment]
Ok, well I am also willing to help maintain this, I was writing my own DI library from scratch when I found this.

Given that the only contributor hasn't been active in what looks like years, what say we fork the main branch, cherrypick trein's changes, and update the build for PyPI.  Not sure if renaming the project is the right call or not, but we could do that to let people still use the original but breathe some new life into it.

Thoughts?

**Comment by ghostsquad** [comment]
@AO-StreetArt What repo/account will the new `pinject` be in? I'm also interested in this project, and would like to contribute compatibility updates so that this works in python 3.5+

**Comment by ankostis** [comment]
I'm not interested anymore.
But I can tell you, don't spend time in these Whitestone.
Start pushing your changes on your account, same name etc, open a wiki and enable issues, and when you have it ready, add a new comment or issue here announcing that the project had "moved"; everybody will check the commits in the network diagram and deduce that your claim is accurate. 
Well done, you be just became the new maintainer!

**Comment by trein** [comment]
I can maintain. Will do some housekeeping today on https://github.com/trein/pinject. Feel free to contribute.

**Comment by zixia** [comment]
@trein I saw your fork had already supported Python 3.

Did you publish your version via pip? 

How could I install your new `pinject` to my project? 

BTW: I suggest you open Issuee & Wiki on your forked project, so we can disscuss over there.

Thanks.

**Comment by trein** [comment]
@zixia I enabled Issues and Wiki.

Regarding publication, I'm not sure if I can publish my fork under the original `pinject` project. I might need to create a new one. I'm open to other ideas/discuss further.

**Comment by trein** [comment]
@zixia Agreed. Let's wait for @KurtSteinkraus's response for a few days.

**Comment by zixia** [comment]
https://api.github.com/users/KurtSteinkraus No Email... 

Could we find any way to contact him?

**Comment by honorabel** [comment]
Would love to hear if there are any updates on this project having a new maintainer!

**Comment by zixia** [comment]
Yes, I'd  like to raise my hand for volunteer.

And also I feel it's the time to consider fork a new one to go ahead, is there any one want to do it for us? ;)

**Comment by honorabel** [comment]
I support creating a new fork.  I'm not sure I can yet put my hand up to be the maintainer, but I'm happy to consult and maybe help address bugs.  

I'd like to put a strong vote up to make sure that any python 3.x support work that might be done in the future ensure that existing 2.x support is maintained.

**Comment by trein** [comment]
@honorabel I'm maintaining a [fork](https://github.com/trein/pinject). All these changes have been merged already.

**Comment by zixia** [comment]
@trein Awesome, so we could pip install from your git repository!

**Comment by zixia** [comment]
BTW: I had asked my friends who worked at Google to help us contact @KurtSteinkraus by email. 

Hope we can get him back here!

**Comment by zixia** [comment]
Update: I had contacted with the @KurtSteinkraus via my friends in Google in March, but it seems that he's too busy to response to me.

I'll send a mail to ping him again, hope he can come back to update the repo, better to add @trein to collaborators.

Or we might have to do a hard fork on this project so that we can get a usable `pinject` with Python 3.x

**Pull request closed without merging**
