### PR TITLE
Allow numbers and single letter words in class names (fixes #46)

### LINKED ISSUE #46: Class names cannot contain numbers nor single letter words
The default translation from class names to argument names cannot handle class names containing numbers.

Example. If you run this:

```
from pinject import new_object_graph

class Model1:
    pass

class Obj:
    def __init__(self, model1):
        pass


graph = new_object_graph()

obj = graph.provide(Obj)
```

You get this error:
```
nothing injectable for the binding name "model1" (unannotated)
```

The same appens if the class name contains a single letter camel case word such as `ModelA`:

```
from pinject import new_object_graph

class ModelA:
    pass

class Obj:
    def __init__(self, model_a):
        pass


graph = new_object_graph()

obj = graph.provide(Obj)
```

It fails too:
```
nothing injectable for the binding name "model_a" (unannotated)
```

You can solve the issue by passing a customized `get_arg_names_from_class_name` like this:

```
import re

def get_arg_names_from_class_name_with_nums(class_name):
    parts = []
    rest = class_name
    if rest.startswith('_'):
        rest = rest[1:]
    while True:
        m = re.match(r'([A-Z][a-z]*|[0-9][a-z0-9]*)(.*)', rest)
        if m is None:
            break
        parts.append(m.group(1))
        rest = m.group(2)
    if not parts:
        return []
    return ['_'.join(part.lower() for part in parts)]

graph = new_object_graph(get_arg_names_from_class_name=get_arg_names_from_class_name_with_nums)

obj = graph.provide(Obj)
```

I have prepared a pull request to fix the default `get_arg_names_from_class_name` like in the example above.

### PR DESCRIPTION
**Pull request by davidcim**
Fixes issue #46

### CODE REVIEW

**Comment by davidcim** [comment]
@googlebot I signed it!

**Comment by davidcim** [comment]
`Travis CI` failed to build it for Python 3.3. It seems that there is something broken in Travis:
```
 curl -sSf --retry 5 -o python-3.3.tar.bz2 ${archive_url}

curl: (22) The requested URL returned error: 404 Not Found

Unable to download 3.3 archive. The archive may not exist. Please consider a different version.
```

**Comment by davidcim** [comment]
Test added!

Cheers.

**Comment by davidcim** [comment]
I have added two new commits to this PR by mistake. I was working on another issue that I have found but I should have created a new branch to isolate it and I didn't :(. The new issue is that pinject fails to translate class names with single letter camel case words. For example FooA camel case is not translated to foo_a snake case.

What should I do?... update this PR or delete it and then add two new PRs?.

**Comment by davidcim** [comment]
Since both issues are closely related, I have opted to join them in a single PR. I have also updated the linked issue.

**Comment by davidcim** [comment]
I have remade the PR because I didn't like how numbers were being translated, always as if they were lowercase letters. Now it behaves better IMO. Have a look at the 3 new unit tests:  numbers at the end, numbers followed by lowercase letters and numbers followed by a new word.

**Comment by huan** [comment]
Thank you very much for the contribution!

This change will be publish to the [prerelease](https://pypi.org/project/pinject/#history) `0.15.dev2` with CI/CD, please feel to let me know if you have any questions.

**Pull request merged**
