### PR TITLE
[issue #7] Introduce support to Python 3.x

### PR DESCRIPTION
**Pull request by trein**
- Add Six package, a simple utilities for wrapping over differences
  between Python 2 and Python 3
- Encapsulate compatibility methods in 'support.py' module
- Introduce unit tests for 'support.py' module

Review needed for two failing tests on Python 2.7.x and 3.x:
- test_unknown (pinject.locations_test.GetClassNameAndLocTest)
- test_unknown (pinject.locations_test.GetTypeLocTest)

### CODE REVIEW

**Comment by moltob** [comment]
Please merge. Would be greatly appreciated!

**Comment by m3drano** [comment]
:+1:

**Comment by ankostis** [comment]
Is anybody maintaining this project?

**Comment by marceloavan** [comment]
@ankostis I do not think so.

**Pull request closed without merging**
