### PR TITLE
Handle find_classes_in_module when module.__bases__ is not a tuple

### PR DESCRIPTION
**Pull request by creamy-seas**
## Issue with import of `tensorboard` library (and perceivably some others too) ##

For context, the issue arose when I attempted to use `tensorboard` (a dependecy of `tensorflow`) for a machine learning project. 

Importing `tensorflow` in any of the files that are imported to build the object graph, results in the following error:

```text
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    OBJ_GRAPH = pinject.new_object_graph()
  File "/Users/CCCP/.config/python_vi/tf/lib/python3.7/site-packages/pinject/object_graph.py", line 100, in new_object_graph
    found_classes = finding.find_classes(modules, classes)
  File "/Users/CCCP/.config/python_vi/tf/lib/python3.7/site-packages/pinject/finding.py", line 32, in find_classes
    all_classes |= _find_classes_in_module(module)
  File "/Users/CCCP/.config/python_vi/tf/lib/python3.7/site-packages/pinject/finding.py", line 46, in _find_classes_in_module
    for member_name, member in inspect.getmembers(module):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 364, in getmembers
    for base in object.__bases__:
TypeError: 'int' object is not iterable
```

## Recreation ##
A bare-bone recreation of the bug can be achieved with
```python
import pinject
import tensorflow as tf

class ExampleClass:
    pass

OBJ_GRAPH = pinject.new_object_graph()
example_class = OBJ_GRAPH.provide(ExampleClass)
```

and the following requirements file:
<details>
<summary><b>requirements.txt</b></summary>

```text
absl-py==0.9.0
astunparse==1.6.3
attrs==19.3.0
cachetools==4.1.0
certifi==2020.6.20
chardet==3.0.4
decorator==4.4.2
gast==0.3.3
google-auth==1.18.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.30.0
h5py==2.10.0
idna==2.9
importlib-metadata==1.7.0
Keras-Preprocessing==1.1.2
Markdown==3.2.2
mock==4.0.2
more-itertools==8.4.0
numpy==1.19.0
oauthlib==3.1.0
opt-einsum==3.2.1
packaging==20.4
pinject==0.14.1
pluggy==0.13.1
protobuf==3.12.2
py==1.9.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
pytest==5.4.3
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scipy==1.4.1
semver==2.10.2
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
urllib3==1.25.9
wcwidth==0.2.5
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0
```
</details>

## Issue ##
The error arises inside the [`inspect.getmembers()`](https://github.com/python/cpython/blob/3.8/Lib/inspect.py#L325) function called in [finding.py](https://github.com/google/pinject/blob/master/pinject/finding.py#L46):
- It attempts to iterate through the `module.__bases__` attribute of the `module` that is passed into it from [finding.py](https://github.com/google/pinject/blob/master/pinject/finding.py#L46)
- However running the following import in `module.__bases__` attribute being an integer - **not a tuple that is expected** 
```python
# tensorboard 2.2.2
from tensorboard.compat.tensorflow_stub import pywrap_tensorflow
assert pywrap_tensorflow.__bases__ == 0
```
> This is somewhat peculiar, as an attempt to override `__bases__` of a class:
> ```python
> class ExampleClass(object):
>            pass
> ExampleClass.__bases__ = 0
> ```
> throws `TypeError: can only assign tuple to SomeClass.__bases__, not int`

- As a result a `TypeError: 'int' object is not iterable` error is raised
- [Relevant section of the code](https://github.com/google/pinject/blob/master/pinject/finding.py#L46):
```python
def _find_classes_in_module(module):
    classes = set()
    for member_name, member in inspect.getmembers(module):
        try:
            if inspect.isclass(member) and not member_name == "__class__":
                classes.add(member)
        except NameError:
            # In Python 3 calling isinstance() on SWIG's global cvar property
            # raises:
            #     "NameError: Unknown C global variable"
            # In that case just continue, otherwise let the Error through.
            if not member_name == "cvar":
                raise
    return classes
```

## Patch ##
Since such a `__bases__` issue can foreseeably occur in other libraries, my proposition is for a simple patch that would pre-empt `module.__bases__` being of an incorrect format, and set an empty tuple so as to bypass this problem, but allow the rest of [`inspect.getmembers()`](https://github.com/python/cpython/blob/3.8/Lib/inspect.py#L325) to execute as expected.
```python
def _find_classes_in_module(module):
    classes = set()

    try:
        if not isinstance(module.__bases__, tuple):
            module.__bases__ = ()
    except AttributeError:
        pass

    for member_name, member in inspect.getmembers(module):
        try:
            if inspect.isclass(member) and not member_name == '__class__':
                classes.add(member)
        except NameError:
            # In Python 3 calling isinstance() on SWIG's global cvar property
            # raises:
            #     "NameError: Unknown C global variable"
            # In that case just continue, otherwise let the Error through.
            if not member_name == 'cvar':
                raise
    return classes

```

### CODE REVIEW

**Comment by creamy-seas** [comment]
@googlebot I signed it!

**Comment by huan** [comment]
It's great to see that you are using the pinject with TensorFlow!

Cloud you please add some related unit tests which can cover the code in your PR so that we can make sure everything is ok and expected?

**Comment by creamy-seas** [comment]
Oh, I really feel that pinject is the ultimate funnel for constraining monoliths of code:
- Typically written by developers coming in from physics/maths backgrounds
- Or from the online machine learning courses
- Where stacks and stacks of optimisers, data preparatory steps, training, testing and execution pipelines are bundled into a tower-of-a-file

With a clear oo-structure embedded in the framework, combined with singleton instances that are passed around the program, it is so much easier to separate out the different modules of a pipeline in an easy to explain layout.

---
Ah, emotions over - I have added the unittest that tests specifically a case of the `__bases__` not being a tuple - recreating what is occurring with `tensorboard`.
```python
def test__find_classes_in_module_when_module_bases_is_not_tuple(self):
    this_module = sys.modules[FindClassesTest.__module__]
    this_module.__bases__ = 0
    self.assertIn(FindClassesTest,
                  finding.find_classes(modules=[this_module], classes=None))
```
---
I also confirm that from the [official documentation](https://docs.python.org/3/reference/datamodel.html) `__bases__` is indeed meant to be a tuple. I am yet to figure out what exactly is causing this non-standard behaviour in `tensorboard`, but given this occurence, this might be a common issue with other packages as well.

**Comment by huan** [comment]
@googlebot I consent.

**Comment by huan** [comment]
Thank you very much for your contribution!

This PR should have already been living at https://pypi.org/project/pinject/0.15.dev4/

**Pull request merged**
